[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
image = { version = "0.25.6", features = ["jpeg", "png"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
egui_extras = { version = "0.27", features = ["all_loaders"] }


