[package]
name = "dealer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
itertools = "0.14.0"
mongodb = "3.2.3"
once_cell = "1.17"
rand = "0.8"
serde_json = "1.0.140"
tokio = "1.44.1"
